// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import {IncrementalMerkleTree, Poseidon2, Field} from "./IncrementalMerkleTree.sol";

/// @notice Honk verifier interface (matches HonkVerifier generated by bb).
interface IHonkVerifier {
    function verify(bytes calldata _proof, bytes32[] calldata _publicInputs) external view returns (bool);
}

/**
 * @title PrivateRaffle
 * @notice Merkle-based private raffle with verifiable shuffle.
 *
 * @dev Claim circuit pubSignals order:
 *      [0] root
 *      [1] nullifier_hash
 *      [2] recipient_binding
 *      [3] raffle_id
 *      [4] winner_index
 *      [5] tree_depth
 *
 * @dev Shuffle circuit pubSignals order:
 *      [0] pending_root
 *      [1] final_root
 *      [2] alias_root
 *      [3] raffle_id
 *      [4] n_participants
 *      [5] tree_depth
 *      [6] operator_secret_hash
 *      [7] vrf_output
 */
contract PrivateRaffle is IncrementalMerkleTree {
    struct Raffle {
        uint256 levels;              // Merkle height
        uint256 ticketPrice;         // wei
        uint256 maxSize;             // 2^levels
        bool open;                   // selling tickets
        bool winnerSet;              // winnerIndex finalized
        uint256 winnerIndex;         // 0..nextIndex-1
        uint256 prizePool;           // wei
        bytes32 shuffleSecretHash;   // H(DOMAIN_SECRET, operator_secret), committed before VRF
        uint256 vrfRandomness;       // Raw VRF output
        bytes32 finalRoot;           // Root of shuffled commitments (post-finalize)
        bytes32 aliasRoot;           // Root of shuffled aliases (post-finalize)
        bool finalized;              // Whether finalizeRaffle has been called
    }

    address public owner;
    IHonkVerifier public claimVerifier;
    IHonkVerifier public shuffleVerifier;

    /// @notice Domain separation constant for recipient binding: "BIND_V1"
    uint256 public constant DOMAIN_BIND = 0x42494e445f5631;

    /// @notice Domain separation constant for entry hashes: "ENTRY_V1"
    uint256 public constant DOMAIN_ENTRY = 0x454e5452595f5631;

    // raffleId => Raffle
    mapping(uint256 => Raffle) public raffles;

    // Optional audit trail: (raffleId, index) -> commitment (leaf)
    mapping(uint256 => mapping(uint256 => uint256)) public commitments;

    // Double-claim protection: (raffleId, nullifierHash) -> used
    mapping(uint256 => mapping(uint256 => bool)) public nullifiers;

    /* ───────────────────────────── Events ────────────────────────────── */

    event RaffleCreated(
        uint256 indexed raffleId,
        uint256 ticketPrice,
        uint256 levels,
        uint256 maxSize
    );
    event TicketDeposited(
        uint256 indexed raffleId,
        uint256 index,
        uint256 commitment
    );
    event RaffleClosed(uint256 indexed raffleId, uint256 winnerIndex);
    event PrizeClaimed(
        uint256 indexed raffleId,
        address indexed to,
        uint256 amount,
        uint256 nullifierHash
    );
    event ShuffleSecretCommitted(uint256 indexed raffleId, bytes32 secretHash);
    event RaffleFinalized(uint256 indexed raffleId, bytes32 finalRoot, bytes32 aliasRoot);

    /* ───────────────────────────── Errors ────────────────────────────── */

    error ShuffleSecretNotCommitted();
    error ShuffleSecretAlreadyCommitted();
    error VRFNotReceived();
    error AlreadyFinalized();
    error NotFinalized();
    error InvalidFinalizeProof();

    /* ──────────────────────────── Modifiers ──────────────────────────── */

    modifier onlyOwner() {
        require(msg.sender == owner, "ONLY_OWNER");
        _;
    }

    /* ─────────────────────────── Constructor ─────────────────────────── */

    constructor(
        address poseidon2Addr,
        address claimVerifierAddr,
        address shuffleVerifierAddr
    ) IncrementalMerkleTree(Poseidon2(poseidon2Addr)) {
        owner = msg.sender;
        claimVerifier = IHonkVerifier(claimVerifierAddr);
        shuffleVerifier = IHonkVerifier(shuffleVerifierAddr);
    }

    /* ───────────────────────────── Admin ───────────────────────────── */

    /**
     * @notice Create a raffle with fixed capacity (2^levels) and ticket price.
     * @param raffleId Unique identifier.
     * @param ticketPrice Price per ticket (wei).
     * @param levels Merkle height (capacity = 2^levels).
     */
    function createRaffle(
        uint256 raffleId,
        uint256 ticketPrice,
        uint256 levels
    ) external onlyOwner {
        require(raffles[raffleId].ticketPrice == 0, "RAFFLE_EXISTS");
        require(levels > 0 && levels <= MAX_DEPTH, "LEVELS_RANGE");

        uint256 maxSize = uint256(1) << levels;

        Raffle storage r = raffles[raffleId];
        r.levels = levels;
        r.ticketPrice = ticketPrice;
        r.maxSize = maxSize;
        r.open = true;

        // Initialize the incremental Merkle tree for this raffle
        _initTree(raffleId, uint32(levels));

        emit RaffleCreated(raffleId, ticketPrice, levels, maxSize);
    }

    /**
     * @notice Commit the shuffle secret hash before VRF randomness is received.
     * @dev Must be called after ticket sales are closed but before finalizeRaffle.
     *      secretHash = H(DOMAIN_SECRET, operator_secret).
     */
    function commitShuffleSecret(uint256 raffleId, bytes32 secretHash) external onlyOwner {
        Raffle storage r = raffles[raffleId];
        require(r.ticketPrice != 0, "RAFFLE_UNKNOWN");
        require(!r.open, "STILL_OPEN");
        require(getNextLeafIndex(raffleId) > 0, "NO_TICKETS");
        require(r.shuffleSecretHash == bytes32(0), "SECRET_ALREADY_COMMITTED");

        r.shuffleSecretHash = secretHash;
        emit ShuffleSecretCommitted(raffleId, secretHash);
    }

    /**
     * @notice Close ticket sales and store VRF randomness.
     * @dev In production, randomness comes from Supra dVRF callback.
     *      Winner index is NOT set here; it is calculated in finalizeRaffle.
     */
    function closeRaffle(uint256 raffleId, uint256 randomness) external onlyOwner {
        Raffle storage r = raffles[raffleId];
        require(r.ticketPrice != 0, "RAFFLE_UNKNOWN");
        require(r.open, "ALREADY_CLOSED");
        require(getNextLeafIndex(raffleId) > 0, "NO_TICKETS");

        r.open = false;
        r.vrfRandomness = randomness;
    }

    /**
     * @notice Finalize the raffle by verifying the shuffle proof.
     * @dev Verifies the shuffle proof against on-chain state, then stores
     *      the final commitment root, alias root, and winner index.
     */
    function finalizeRaffle(
        uint256 raffleId,
        bytes calldata shuffleProof,
        bytes32[] calldata shufflePublicInputs
    ) external onlyOwner {
        Raffle storage r = raffles[raffleId];
        uint32 nextIdx = getNextLeafIndex(raffleId);

        require(r.ticketPrice != 0, "RAFFLE_UNKNOWN");
        require(!r.open, "STILL_OPEN");
        require(!r.finalized, "ALREADY_FINALIZED");
        require(r.shuffleSecretHash != bytes32(0), "SECRET_NOT_COMMITTED");
        require(r.vrfRandomness != 0, "VRF_NOT_RECEIVED");

        // Verify shuffle proof public inputs match on-chain state
        require(shufflePublicInputs.length == 8, "BAD_INPUTS_LEN");
        require(shufflePublicInputs[0] == getLastRoot(raffleId), "PENDING_ROOT_MISMATCH");
        require(uint256(shufflePublicInputs[3]) == raffleId, "RAFFLE_ID_MISMATCH");
        require(uint256(shufflePublicInputs[4]) == uint256(nextIdx), "N_MISMATCH");
        require(uint256(shufflePublicInputs[5]) == r.levels, "DEPTH_MISMATCH");
        require(shufflePublicInputs[6] == r.shuffleSecretHash, "SECRET_HASH_MISMATCH");
        require(uint256(shufflePublicInputs[7]) == r.vrfRandomness, "VRF_MISMATCH");

        // Verify the shuffle proof
        require(shuffleVerifier.verify(shuffleProof, shufflePublicInputs), "BAD_SHUFFLE_PROOF");

        // Store final roots
        r.finalRoot = shufflePublicInputs[1]; // final_root
        r.aliasRoot = shufflePublicInputs[2]; // alias_root

        // Calculate winner index
        r.winnerIndex = r.vrfRandomness % uint256(nextIdx);
        r.winnerSet = true;
        r.finalized = true;

        emit RaffleFinalized(raffleId, r.finalRoot, r.aliasRoot);
        emit RaffleClosed(raffleId, r.winnerIndex);
    }

    /**
     * @notice Close and finalize without shuffle proof (for testing/small raffles).
     * @dev The on-chain tree stores entry_hashes, but the claim circuit verifies
     *      against raw commitments. The operator provides the commitment-only root.
     *      This is a trusted-operator path (no ZK proof required).
     * @param commitmentRoot Root of the Merkle tree of raw commitments (computed off-chain).
     */
    function closeAndFinalizeSimple(uint256 raffleId, uint256 randomness, bytes32 commitmentRoot) external onlyOwner {
        Raffle storage r = raffles[raffleId];
        uint32 nextIdx = getNextLeafIndex(raffleId);

        require(r.ticketPrice != 0, "RAFFLE_UNKNOWN");
        require(r.open, "ALREADY_CLOSED");
        require(nextIdx > 0, "NO_TICKETS");

        r.open = false;
        r.vrfRandomness = randomness;
        r.finalRoot = commitmentRoot;
        r.winnerIndex = randomness % uint256(nextIdx);
        r.winnerSet = true;
        r.finalized = true;

        emit RaffleClosed(raffleId, r.winnerIndex);
    }

    /* ─────────────────────────── User actions ───────────────────────── */

    /**
     * @notice Buy a ticket by submitting a commitment (leaf).
     * @dev Use a relayer if caller privacy is required.
     */
    function depositTicket(
        uint256 raffleId,
        uint256 commitment
    ) external payable {
        Raffle storage r = raffles[raffleId];
        require(r.ticketPrice != 0, "RAFFLE_UNKNOWN");
        require(r.open, "CLOSED");
        require(msg.value == r.ticketPrice, "BAD_PRICE");

        // Compute entry_hash = H(DOMAIN_ENTRY, commitment, nextIndex)
        // The tree stores entry_hashes (not raw commitments) so the shuffle circuit
        // can verify pending_root matches on-chain state.
        uint256 nextIdx = uint256(getNextLeafIndex(raffleId));
        bytes32 entryHash = Field.toBytes32(
            HASHER.hash_3(
                Field.toField(DOMAIN_ENTRY),
                Field.toField(commitment),
                Field.toField(nextIdx)
            )
        );

        // Insert entry_hash into the incremental Merkle tree
        uint32 insertedIndex = _insert(raffleId, entryHash);

        // Store raw commitment for audit trail
        commitments[raffleId][uint256(insertedIndex)] = commitment;
        r.prizePool += msg.value;

        emit TicketDeposited(raffleId, uint256(insertedIndex), commitment);
    }

    /**
     * @notice Claim the prize if your leaf corresponds to the published winner index.
     * @dev Verifies Honk proof, winner index, recipient binding, and nullifier uniqueness.
     *      Proof is verified against the post-shuffle finalRoot.
     */
    function claimPrize(
        bytes calldata claimProof,
        bytes32[] calldata claimPublicInputs,
        address recipient
    ) external {
        require(claimPublicInputs.length == 6, "BAD_PUBSIG_LEN");

        // Verify the claim proof
        require(claimVerifier.verify(claimProof, claimPublicInputs), "BAD_PROOF");

        // Parse pubSignals
        uint256 root = uint256(claimPublicInputs[0]);
        uint256 nullifierHash = uint256(claimPublicInputs[1]);
        uint256 recipientBinding = uint256(claimPublicInputs[2]);
        uint256 raffleId = uint256(claimPublicInputs[3]);
        uint256 winnerIdx = uint256(claimPublicInputs[4]);
        uint256 treeDepth = uint256(claimPublicInputs[5]);

        Raffle storage r = raffles[raffleId];
        require(r.ticketPrice != 0, "RAFFLE_UNKNOWN");
        require(!r.open && r.finalized, "NOT_FINALIZED");
        require(treeDepth == r.levels, "DEPTH_MISMATCH");

        // Verify root against the post-shuffle final root
        require(root == uint256(r.finalRoot), "ROOT_MISMATCH");
        require(winnerIdx == r.winnerIndex, "NOT_WINNER");

        // Bind recipient to the proof: Poseidon3(DOMAIN_BIND, nullifierHash, recipient)
        uint256 rb = Field.Type.unwrap(
            HASHER.hash_3(
                Field.toField(DOMAIN_BIND),
                Field.toField(nullifierHash),
                Field.toField(uint256(uint160(recipient)))
            )
        );
        require(recipientBinding == rb, "RECIPIENT_NOT_BOUND");

        // Prevent double-claim
        require(!nullifiers[raffleId][nullifierHash], "ALREADY_CLAIMED");
        nullifiers[raffleId][nullifierHash] = true;

        // Effects-before-interactions
        uint256 amount = r.prizePool;
        r.prizePool = 0;

        (bool sent, ) = recipient.call{value: amount}("");
        require(sent, "SEND_FAILED");

        emit PrizeClaimed(raffleId, recipient, amount, nullifierHash);
    }

    /* ───────────────────────────── Utilities ─────────────────────────── */

    function getRoot(uint256 raffleId) external view returns (bytes32) {
        return getLastRoot(raffleId);
    }

    function getRaffleCore(uint256 raffleId) external view returns (
        uint256 levels,
        uint256 ticketPrice,
        uint256 maxSize,
        uint256 nextIndex,
        bytes32 root,
        bool open,
        bool winnerSet,
        uint256 winnerIndex,
        uint256 prizePool
    ) {
        Raffle storage r = raffles[raffleId];
        return (r.levels, r.ticketPrice, r.maxSize,
                uint256(getNextLeafIndex(raffleId)), getLastRoot(raffleId),
                r.open, r.winnerSet, r.winnerIndex, r.prizePool);
    }

    function getRaffleExtra(uint256 raffleId) external view returns (
        bytes32 shuffleSecretHash,
        uint256 vrfRandomness,
        bytes32 finalRoot,
        bytes32 aliasRoot,
        bool finalized
    ) {
        Raffle storage r = raffles[raffleId];
        return (r.shuffleSecretHash, r.vrfRandomness, r.finalRoot, r.aliasRoot, r.finalized);
    }

    function setOwner(address newOwner) external onlyOwner {
        owner = newOwner;
    }

    /// @dev Emergency drain. Avoid using in production unless strictly necessary.
    function emergencyWithdraw(address to, uint256 amount) external onlyOwner {
        (bool ok, ) = to.call{value: amount}("");
        require(ok, "WITHDRAW_FAIL");
    }

    receive() external payable {}
}
